[aws]
symbol = "  "

[cmd_duration]
min_time = 1_000
style = "bold white"

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
read_only = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hostname]
style = "underline blue"
format = "@[$hostname]($style) "
ssh_only = false

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[perl]
symbol = " "

[php]
format = " [$symbol($version )]($style)"
symbol = " "

[python]
format = ' [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "

[username]
show_always = true
style_root = "bold red"
style_user = "bold green"
format = "[$user]($style)"